name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload Release
        uses: ncipollo/release-action@v1.14.0
        with:
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: '.github/RELEASE_BODY.md'
